### ISSUE TITLE
Texture misalignment

### ISSUE THREAD

**Issue by anastasia-tkach** [ph4m/DepthSenseGrabber#1]
Hello,
Thank you for posting the code for color and depth images alignment.
I have encountered problem when running it, as you can see on the screen short, some of my fingers appear twice on the picture. 
![screenshot from 2015-01-04 13 55 22](https://cloud.githubusercontent.com/assets/8734517/5606046/f3e5e164-941a-11e4-8ba4-3b5fc77b0f25.png)
Could you please tell if you have run into the same problem? Do you, maybe, have a suggestion how to fix it?
Thank you in advance.

**Comment by ph4m** [comment]
Hi,

Thank you for your message and reporting that issue.
Indeed I also ran into it. Basically, what happens is that in addition to each pixel of the depth map, the camera also provides the coordinates of the "corresponding" pixel of the color map. For some reason, significantly non-adjacent depth pixels seem to be assigned the same color value, hence some of your fingers are "repeated" on the right.
This problem is actually directly due to the camera, as you can see the problem also appears with the Softkinetic's DepthSenseViewer application included in the SDK:
![uv](https://cloud.githubusercontent.com/assets/4465529/5606218/8fc02f32-9424-11e4-96cc-457441940ddd.png)

Looking further into it, I noticed that you could filter out most of the repeated pixels by increasing the confidence threshold, and making sure the color pixel is only reproduced if the depth data is reliable "enough" (a threshold value of 150 seems to do the trick, see https://github.com/ph4m/DepthSenseGrabber/blob/master/DepthSenseGrabberSO/DepthSenseGrabberSO.cxx#L32).
Here is what I now get as a color map synchronised with the depth original acquisition (parameters bool saveColorSyncFlag and bool saveDepthAcqFlag):
![colorsynctodepth](https://cloud.githubusercontent.com/assets/4465529/5606399/204c5950-942e-11e4-87a0-8dbcb0396e79.png)

The drawback of this approach is that you lose quite a lot of meaningful color information while the inaccuracies are solely on the depth measurements. Another approach you may consider is, conversely, to use the original color acquisition and synchronise the depth map with it (parameters bool saveColorAcqFlag and bool saveDepthSyncFlag):
![depthsynctocolor](https://cloud.githubusercontent.com/assets/4465529/5606411/a7bcfe94-942e-11e4-826a-314c592dce49.png)

I committed the corresponding fix for the stand-alone version (see https://github.com/ph4m/DepthSenseGrabber/commit/249849b8db25f251cde699c23139d7ce726bc30b). If you need, I can patch the OpenCV and PCL versions as well but it would need some catching up as some functionalities are so far only implemented in DepthSenseGrabberSO, so I can't say for sure when I'll have time for it. But of course, feel free to fork the repo and update it accordingly.

Let me know if this answered your questions or if you need anything else!

Regards,

**Comment by anastasia-tkach** [comment]
Thank you for such a prompt and comprehensive answer. I am going to use your suggestion and synchronize depth map with color image instead. This helps a lot!
